export const userData =[
  {
    "id": 1,
    "name": "Person 1",
    "age": 22,
    "education": "High School",
    "location": "USA",
    "friends": 284,
    "kudos": "2k",
    "focus_time": "14h",
    "sex": "boy",
    "interests": ["Podcasts", "Gaming", "Cooking"],
    "imageUrl": "https://robohash.org/1.png?set=set1",
    "about": "I'm a random person with id 1."
  },
  {
    "id": 2,
    "name": "Person 2",
    "age": 28,
    "education": "High School",
    "location": "USA",
    "friends": 183,
    "kudos": "2k",
    "focus_time": "9h",
    "sex": "girl",
    "interests": ["Drawing", "Cooking", "Traveling"],
    "imageUrl": "https://robohash.org/2.png?set=set1",
    "about": "I'm a random person with id 2."
  },
  {
    "id": 3,
    "name": "Person 3",
    "age": 19,
    "education": "High School",
    "location": "USA",
    "friends": 142,
    "kudos": "2k",
    "focus_time": "20h",
    "sex": "boy",
    "interests": ["Podcasts", "Cooking", "Reading"],
    "imageUrl": "https://robohash.org/3.png?set=set1",
    "about": "I'm a random person with id 3."
  },
  {
    "id": 4,
    "name": "Person 4",
    "age": 24,
    "education": "High School",
    "location": "USA",
    "friends": 253,
    "kudos": "2k",
    "focus_time": "12h",
    "sex": "girl",
    "interests": ["Podcasts", "Gaming", "Cooking"],
    "imageUrl": "https://robohash.org/4.png?set=set1",
    "about": "I'm a random person with id 4."
  },
  {
    "id": 5,
    "name": "Person 5",
    "age": 21,
    "education": "High School",
    "location": "USA",
    "friends": 167,
    "kudos": "2k",
    "focus_time": "18h",
    "sex": "boy",
    "interests": ["Gaming", "Cooking", "Reading"],
    "imageUrl": "https://robohash.org/5.png?set=set1",
    "about": "I'm a random person with id 5."
  },
  {
    "id": 6,
    "name": "Person 6",
    "age": 20,
    "education": "High School",
    "location": "USA",
    "friends": 265,
    "kudos": "2k",
    "focus_time": "6h",
    "sex": "girl",
    "interests": ["Podcasts", "Drawing", "Gaming"],
    "imageUrl": "https://robohash.org/6.png?set=set1",
    "about": "I'm a random person with id 6."
  },
  {
    "id": 7,
    "name": "Person 7",
    "age": 23,
    "education": "High School",
    "location": "USA",
    "friends": 102,
    "kudos": "2k",
    "focus_time": "22h",
    "sex": "boy",
    "interests": ["Podcasts", "Drawing", "Traveling"],
    "imageUrl": "https://robohash.org/7.png?set=set1",
    "about": "I'm a random person with id 7."
  },
  {
    "id": 8,
    "name": "Person 8",
    "age": 26,
    "education": "High School",
    "location": "USA",
    "friends": 196,
    "kudos": "2k",
    "focus_time": "8h",
    "sex": "girl",
    "interests": ["Podcasts", "Drawing", "Cooking"],
    "imageUrl": "https://robohash.org/8.png?set=set1",
    "about": "I'm a random person with id 8."
  },
  {
    "id": 9,
    "name": "Person 9",
    "age": 29,
    "education": "High School",
    "location": "USA",
    "friends": 126,
    "kudos": "2k",
    "focus_time": "16h",
    "sex": "boy",
    "interests": ["Podcasts", "Gaming", "Cooking"],
    "imageUrl": "https://robohash.org/9.png?set=set1",
    "about": "I'm a random person with id 9."
  },
  {
    "id": 10,
    "name": "Person 10",
    "age": 18,
    "education": "High School",
    "location": "USA",
    "friends": 215,
    "kudos": "2k",
    "focus_time": "10h",
    "sex": "girl",
    "interests": ["Drawing", "Cooking", "Traveling"],
    "imageUrl": "https://robohash.org/10.png?set=set1",
    "about": "I'm a random person with id 10."
  }
]
